#!/bin/sh

# Add the 'heroku' remote if not here already
git remote show heroku >/dev/null 2>&1 \
  # && echo 'Heroku remote exists' \
  || git remote add heroku git@heroku.com:scratchml.git

# To deploy: push to heroku
git push heroku master

